class CustomMessageTask:
    FRIEND_REMOVED = 'FRIEND_REMOVED'
    FRIEND_ADDED = 'FRIEND_ADDED'
    PARTY_INVITE = 'PARTY_INVITE'
    PARTY_REQUEST = 'PARTY_REQUEST'
    PAGE_CHANGED = 'PAGE_CHANGED'