class DivID:
    root = "root"
    basePage = "base-page"
    scripts = "script"
    navbar = "navbar"
    ghost3d = "ghost3d"
    musicTray = "music-tray"
    auth = "auth"
    registerForm = "register-form"
    loginForm = "login-form"
    friendsFull = "friends-content"
    onlineFriends = "online-friend-list"
    offlineFriends = "offline-friend-list"
    partyInvites = "party-invites"
    lobbyPlayerSuffix = "player-"
    partyCode = "party-code"
