class DivID:
    root = "root"
    changingPage = "base-page"
    scripts = "script"
    navbar = "navbar"
    ghost3d = "ghost3d"
    musicTrayHolder = "music-tray-holder"
    auth = "auth"
    registerForm = "register-form"
    loginForm = "login-form"
    chatBox = "chat-box"
    friendsStructure = "friends-content"
    onlineFriends = "online-friend-list"
    offlineFriends = "offline-friend-list"
    partyInvites = "party-invites"
    lobbyPlayerSuffix = "player-"
    lobbyFeatures = "lobby-features"
    partyCode = "party-code"
