class FileNames:
    class JS:
        Universal = "Universal.js"
    class CSS:
        Universal = "Universal.css"
    class HTML:
        BodyBase = "BodyBase.html"
        ExtraHead = "ExtraHead.html"
        UniversalContainer = "UniversalContainer.html"
        Navbar = "navbar.html"
        MusicTray = "MusicTray.html"
        AuthFullPage = "AuthFullPage.html"
        Ghost3d = "Ghost3d.html"
        AuthPre = "AuthPre.html"
        AuthPost = "AuthPost.html"
        AuthForm = "AuthForm.html"
        Register = "Register.html"
        Login = "Login.html"
        FriendsFull = "FriendsFull.html"
        FriendElement = "FriendElement.html"
        PartyInvitesCount = "PartyInvitesCount.html"
        PartyInvitesElement = "PartyInvitesElement.html"
        LobbyFull = "LobbyFull.html"
        LobbyMember = "LobbyMember.html"
        LobbyFeatures = "LobbyFeatures.html"
        NotesFullPage = "NotesFullPage.html"