class FileNames:
    class JS:
        Universal = "Universal.js"
        Friends = "Friends.js"
        Lobby = "Lobby.js"
        Music = "Music.js"
        Trail = "Trail.js"
    class CSS:
        Universal = "Universal.css"
    class HTML:
        BodyBase = "BodyBase.html"
        ExtraHead = "ExtraHead.html"
        UniversalContainer = "UniversalContainer.html"
        Navbar = "navbar.html"
        MusicTray = "MusicTray.html"
        AuthStructure = "AuthFullPage.html"
        Ghost3d = "Ghost3d.html"
        AuthPre = "AuthPre.html"
        AuthPost = "AuthPost.html"
        AuthForms = "AuthForm.html"
        Register = "Register.html"
        Login = "Login.html"
        ChatFull = "ChatFull.html"
        ChatElement = "ChatElement.html"
        FriendsStructure = "FriendsFull.html"
        FriendElement = "FriendElement.html"
        PartyInvitesCount = "PartyInvitesCount.html"
        PartyInvitesElement = "PartyInvitesElement.html"
        LobbyStructure = "LobbyFull.html"
        LobbyMember = "LobbyMember.html"
        LobbyFeatures = "LobbyFeatures.html"
        NotesFullPage = "NotesFullPage.html"