class FileNames:
    class JS:
        PreAuthUniversal = "Universal.js"
        Friends = "Friends.js"
        Auth = "Auth.js"
        Chat = "Chat.js"
        Lobby = "Lobby.js"
        Music = "Music.js"
        Trail = "Trail.js"
    class CSS:
        Universal = "Universal.css"
    class HTML:
        FirstPage = "FirstPage.html"
        UniversalContainer = "UniversalContainer.html"
        RegularNavbar = "RegularNavbar.html"
        LobbyNavbar = "LobbyNavbar.html"
        MusicTray = "MusicTray.html"
        AuthStructure = "AuthStructure.html"
        Ghost3d = "Ghost3d.html"
        AuthPre = "AuthPre.html"
        AuthPost = "AuthPost.html"
        AuthForms = "AuthForm.html"
        Register = "Register.html"
        Login = "Login.html"
        ChatFull = "ChatFull.html"
        ChatElement = "ChatElement.html"
        FriendsStructure = "FriendsFull.html"
        FriendElement = "FriendElement.html"
        PartyInvitesCount = "PartyInvitesCount.html"
        PartyInvitesElement = "PartyInvitesElement.html"
        LobbyStructure = "LobbyFull.html"
        LobbyFeatures = "LobbyFeatures.html"
        NotesFullPage = "NotesFullPage.html"