class FormPurposes:
    submitRegister = "submitRegister"
    submitLogin = "submitLogin"
    submitNote = "submitNote"
    startQuiz = "startQueue"
    submitQuizOption = "submitQuizOption"
    renderPostQuizQuestion = "renderPostQuizQuestion"
    displayNoteContent = "displayNoteContent"
    renderQuizLobby = "preQuiz"
    rendermusicSubCategories = "renderCategories"
    renderAuthPage = "renderAuthPage"
    renderMusicPage = "renderMusicPage"
    renderNotesPage = "renderNotesPage"
    renderContentMarketplacePage = "renderContentMarketplacePage"
