class Pages:
    PRE_AUTH = "Pre-Auth"
    HOMEPAGE = "Post-Auth"
    AUTH = "Auth"
    NAVGRID = "Navgrid"
    LOBBY = "Lobby"
    QUIZ = "Quiz"
    QUIZ_SCOREBOARD = "Quiz-Scoreboard"
    NOTES = "Notes"
    FLASHCARD = "Flashcard"
    MARKETPLACE = "Market-Place"
