class PlayerStatus:
    ONLINE = "Online"
    OFFLINE = "Offline"
    NOTES = "Notes"
    MARKETPLACE = "Marketplace"
    FLASHCARD = "Flashcards"
    LOBBY = "Lobby"
    QUIZ = "Quiz"
    RESULT = "Result"
    CHATBOT = "Chatbot"